FROM python:3.10-alpine

# Set the working directory in the container
WORKDIR /backend_fastapi_app

# Install system dependencies
RUN apk update && \
    apk add --no-cache gcc musl-dev

# Copy the requirements file into the container at /backend_fastapi_app
COPY requirements.txt /backend_fastapi_app/

# Install Python packages from requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /backend_fastapi_app
COPY . /backend_fastapi_app/

# Start application
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]