FROM python:3.10-alpine

# Set the working directory in the container
WORKDIR /sensor_simulator_client

# Install system dependencies
RUN apk update && \
    apk add --no-cache gcc musl-dev

# Copy the requirements file into the container at /sensor_simulator_client
COPY requirements.txt /sensor_simulator_client/

# Install Python packages from requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /sensor_simulator_client
COPY . /sensor_simulator_client/

# Command to start sensor simulator with argument ABS as sensor id and 10 seconds as playbackspeed
CMD ["python", "start_sensor_simulator.py", "ABS", "10"]