FROM python:3.10-alpine

# Set the working directory in the container
WORKDIR /sensor_backend_client

# Install system dependencies
RUN apk update && \
    apk add --no-cache gcc musl-dev

# Copy the requirements file into the container at /sensor_backend_client
COPY requirements.txt /sensor_backend_client/

# Install Python packages from requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /sensor_backend_client
COPY . /sensor_backend_client/

# Command to start backend client with argument backend as client id
CMD ["python", "start_backend_client.py", "backend"]